terraform {
  required_version = ">= 1.5"

  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 3.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

provider "azuread" {}

# ── Data sources ──────────────────────────────────────────────────────
data "azurerm_subscription" "current" {}

# ── Local file outputs ─────────────────────────────────────────────────
# Write combined cert + key PEM to the local machine for the Azure MCP Server.
# SECURITY: The private key is also stored in Terraform state. Use encrypted
# remote state (e.g. Azure Blob + customer-managed key) in shared environments.
# See docs/threat-model.md for full discussion.
resource "local_sensitive_file" "agent_cert_pem" {
  content              = "${tls_self_signed_cert.agent.cert_pem}${tls_private_key.agent.private_key_pem}"
  filename             = pathexpand("~/.config/copilot-agent/agent-cert.pem")
  file_permission      = "0600"
  directory_permission = "0700"
}

# Write a .env.copilot-agent file at the repo root for the shell wrapper to source.
resource "local_sensitive_file" "env_file" {
  content = <<-EOT
    # Generated by Terraform — do not edit manually
    # Service principal: ${var.app_name}
    export AZURE_TENANT_ID="${data.azurerm_subscription.current.tenant_id}"
    export AZURE_CLIENT_ID="${azuread_application.agent.client_id}"
    export AZURE_CLIENT_CERTIFICATE_PATH="${pathexpand("~/.config/copilot-agent/agent-cert.pem")}"
  EOT
  filename        = "${path.module}/../.env.copilot-agent"
  file_permission = "0600"
}
